<?php

  /**
   * @file Core functionality for the book solution pack
   * @author griffinj@lafayette.edu
   *
   */

  //require_once dirname(__FILE__) . '/theme/theme.inc';

/**
 * Implements hook_CMODEL_PID_islandora_object_ingested().
 *
 * Modifies certain datastreams extracted by Apache Tika during Solr indexing
 *
 */
function islandora_dss_large_image_islandora_sp_large_image_cmodel_islandora_object_ingested($object) {

  dpm($object);
  }

/**
 * Implements hook_theme_registry_alter().
 */
function islandora_dss_large_image_theme_registry_alter(&$theme_registry) {

  dpm(array_keys($theme_registry));

  $theme_registry['islandora_large_image']['template'] = drupal_get_path('module', 'islandora_dss_large_image') . '/theme/islandora-large-image';
}